name: 'Spotify GitHub Action Stats'
description: 'Show your spotify stats inside your README.md'
inputs:
outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.example_input }}