name: run main.py

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # install the python version needed
          cache: 'pip'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python main.py
          
      - name: Check for changes # create env variable indicating if any changes were made
        id: git-check
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV 
      - name: Commit and push if changes
        if: env.changes == 'true'
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git commit -m "updated video index"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/GitGinocchio/spotify-stats-action.git
